// WebDisplay/src/components/dashboard-item/main.tsx
import './main.scss';

import { PropsWithChildren } from 'react';

type Props = {
    title: string;
};

function DashboardItem(props: PropsWithChildren<Props>) {
    return (
        <>
            <div className="dashboard-item-header bg-primary text-white">
                {props.title}
            </div>
            <div className="dashboard-item-content">{props.children}</div>
        </>
    );
}

export default DashboardItem;

// WebDisplay/src/components/DashboardItem.vue
<script setup lang="ts">
    defineProps(['title']);
</script>

<template>
    <div class="bg-primary dashboard-item-header">
        {{ title }}
    </div>
    <div class="dashboard-item-content">
        <slot></slot>
    </div>
</template>

<style scoped>
    .dashboard-item-header {
        padding: 2px 10px;
    }

    .dashboard-item-content {
        background-color: white;
    }
</style>
