// WebDisplay/src/components/WeatherSummary.vue
<script lang="ts" setup>
    import { ref, watch } from 'vue';
    import { useWeatherStore } from '@/stores/weatherStore';
    import WeatherAggregates from '@/models/weather/weather-aggregates';
    import { ConvertPascalToInchesOfMercury } from '@/pressureConverter';
    import { ShortenWindDirection } from '@/windFormatter';

    const props = defineProps({
        start: { type: Date, required: true },
        end: { type: Date, required: true }
    });

    const weatherAggregates = ref<WeatherAggregates | undefined>();

    const weatherStore = useWeatherStore();

    const load = () => {
        weatherStore.getReadingAggregate(props.start, props.end).then((newWeatherAggregates) => {
            weatherAggregates.value = newWeatherAggregates;
        });
    };

    watch(
        () => [props.start, props.end],
        () => load()
    );

    load();
</script>

<template>
    <div className="weather-summary">
        <div v-if="!weatherAggregates">Loading...</div>
        <table v-else>
            <tbody>
                <tr>
                    <th></th>
                    <th>Minimum</th>
                    <th>Average</th>
                    <th>Maximum</th>
                </tr>
                <tr>
                    <td class="weather-summary-header">Temperature</td>
                    <td>{{ weatherAggregates!.temperature.min.toFixed(2) }}°F</td>
                    <td>{{ weatherAggregates!.temperature.average.toFixed(2) }}°F</td>
                    <td>{{ weatherAggregates!.temperature.max.toFixed(2) }}°F</td>
                </tr>
                <tr>
                    <td class="weather-summary-header">Humidity</td>
                    <td>{{ weatherAggregates!.humidity.min.toFixed(2) }}%</td>
                    <td>{{ weatherAggregates!.humidity.average.toFixed(2) }}%</td>
                    <td>{{ weatherAggregates!.humidity.max.toFixed(2) }}%</td>
                </tr>
                <tr>
                    <td class="weather-summary-header">Pressure</td>
                    <td>{{ ConvertPascalToInchesOfMercury(weatherAggregates!.pressure.min).toFixed(2) }}"</td>
                    <td>{{ ConvertPascalToInchesOfMercury(weatherAggregates!.pressure.average).toFixed(2) }}"</td>
                    <td>{{ ConvertPascalToInchesOfMercury(weatherAggregates!.pressure.max).toFixed(2) }}"</td>
                </tr>
                <tr>
                    <td class="weather-summary-header">Light</td>
                    <td>
                        {{ weatherAggregates!.light.min.toFixed(2) }}
                        lx
                    </td>
                    <td>
                        {{ weatherAggregates!.light.average.toFixed(2) }}
                        lx
                    </td>
                    <td>
                        {{ weatherAggregates!.light.max.toFixed(2) }}
                        lx
                    </td>
                </tr>
                <tr>
                    <td class="weather-summary-header">Wind speed</td>
                    <td>
                        {{ weatherAggregates!.windSpeed.min.toFixed(2) }}
                        mph
                    </td>
                    <td>
                        {{ weatherAggregates!.windSpeed.average.toFixed(2) }}
                        mph
                    </td>
                    <td>
                        {{ weatherAggregates!.windSpeed.max.toFixed(2) }}
                        mph
                    </td>
                </tr>
                <tr>
                    <td class="weather-summary-header">Wind direction</td>
                    <td></td>
                    <td>
                        {{ ShortenWindDirection(weatherAggregates!.windDirectionAverage) }}
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td class="weather-summary-header">Rain</td>
                    <td></td>
                    <td></td>
                    <td>{{ weatherAggregates!.rainTotal.toFixed(2) }}"</td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<style scoped>
    .weather-summary {
        font-size: 14px;
        padding: 6px 12px;
    }

    .weather-summary-header {
        font-weight: 500;
        text-align: right;
        padding-right: 10px;
    }

    th {
        padding-right: 30px;
    }
</style>

// Display/src/app/components/weather/summary/weather-summary.component.ts
import { Component, OnInit } from '@angular/core';
import { TimeSpan } from 'src/app/models/time-span';
import { WeatherService } from 'src/app/services/weather/weather.service';
import { WeatherAggregates } from 'src/app/models/weather/weather-aggregates';

import * as moment from 'moment';

@Component({
    selector: 'app-weather-summary',
    templateUrl: './weather-summary.component.html',
    styleUrls: ['./weather-summary.component.scss']
})
export class WeatherSummaryComponent implements OnInit {

    public loading = true;
    public weatherAggregates: WeatherAggregates = null;

    private timeSpanValue: TimeSpan = TimeSpan.Last24Hours;
    private dateValue: moment.Moment = moment().startOf('day');

    public get timeSpan(): TimeSpan {
        return this.timeSpanValue;
    }
    public set timeSpan(value: TimeSpan) {
        if (this.timeSpanValue === value) {
            return;
        }
        this.timeSpanValue = value;
        this.load();
    }

    public get date(): moment.Moment {
        return this.dateValue;
    }
    public set date(value: moment.Moment) {
        if (this.dateValue === value) {
            return;
        }
        this.dateValue = value;
        this.load();
    }

    constructor(private weatherService: WeatherService) { }

    ngOnInit(): void {
        this.load();
    }

    public async load() {
        let start: moment.Moment;
        let end: moment.Moment;

        this.loading = true;

        switch (this.timeSpan) {
            case TimeSpan.Last24Hours: {
                start = moment().subtract(24, 'hour');
                end = moment();

                break;
            }

            case TimeSpan.Day: {
                start = moment(this.date).startOf('day');
                end = moment(this.date).endOf('day');

                break;
            }

            default: {
                return;
            }
        }

        this.weatherAggregates = await this.weatherService.getReadingAggregate(start, end);

        this.loading = false;
    }
}

<mat-spinner *ngIf="loading" class="content-spinner" strokeWidth="5"></mat-spinner>

<div class="content">
    <header class="header">
        <button id="refresh" mat-button (click)="load()" [disabled]="loading">
            <mat-icon>refresh</mat-icon>
        </button>

        <app-time-range [loading]="loading" [(timeSpan)]="timeSpan" [(date)]="date"></app-time-range>
    </header>

    <div class="body">
        <div *ngIf="loading">
            Loading...
        </div>

        <div *ngIf="!loading && weatherAggregates === null">
            No Data
        </div>

        <div *ngIf="!loading && weatherAggregates !== null">
            <table>
                <tr>
                    <th>

                    </th>
                    <th>
                        Minimum
                    </th>
                    <th>
                        Average
                    </th>
                    <th>
                        Maximum
                    </th>
                </tr>
                <tr>
                    <td class="weather-summary-header">
                        Temperature
                    </td>
                    <td>
                        {{ weatherAggregates.temperature.min.toFixed(2) }}°F
                    </td>
                    <td>
                        {{ weatherAggregates.temperature.average.toFixed(2) }}°F
                    </td>
                    <td>
                        {{ weatherAggregates.temperature.max.toFixed(2) }}°F
                    </td>
                </tr>
                <tr>
                    <td class="weather-summary-header">
                        Humidity
                    </td>
                    <td>
                        {{ weatherAggregates.humidity.min.toFixed(2) }}%
                    </td>
                    <td>
                        {{ weatherAggregates.humidity.average.toFixed(2) }}%
                    </td>
                    <td>
                        {{ weatherAggregates.humidity.max.toFixed(2) }}%
                    </td>
                </tr>
                <tr>
                    <td class="weather-summary-header">
                        Pressure
                    </td>
                    <td>
                        {{ (weatherAggregates.pressure.min / 33.864 / 100).toFixed(2) }}"
                    </td>
                    <td>
                        {{ (weatherAggregates.pressure.average / 33.864 / 100).toFixed(2) }}"
                    </td>
                    <td>
                        {{ (weatherAggregates.pressure.max / 33.864 / 100).toFixed(2) }}"
                    </td>
                </tr>
                <tr>
                    <td class="weather-summary-header">
                        Light
                    </td>
                    <td>
                        {{ weatherAggregates.light.min.toFixed(2) }} lx
                    </td>
                    <td>
                        {{ weatherAggregates.light.average.toFixed(2) }} lx
                    </td>
                    <td>
                        {{ weatherAggregates.light.max.toFixed(2) }} lx
                    </td>
                </tr>
                <tr>
                    <td class="weather-summary-header">
                        Wind Speed
                    </td>
                    <td>
                        {{ weatherAggregates.windSpeed.min.toFixed(2) }} mph
                    </td>
                    <td>
                        {{ weatherAggregates.windSpeed.average.toFixed(2) }} mph
                    </td>
                    <td>
                        {{ weatherAggregates.windSpeed.max.toFixed(2) }} mph
                    </td>
                </tr>
                <tr>
                    <td class="weather-summary-header">
                        Wind Direction
                    </td>
                    <td>
                    </td>
                    <td>
                        {{ weatherAggregates.windDirectionAverage }}
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td class="weather-summary-header">
                        Rain
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                        {{ weatherAggregates.rainTotal.toFixed(2) }}"
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
