// Display/src/app/components/weather/almanac/almanac.component.ts
import { Component, OnInit } from '@angular/core';
import { WeatherUpdate } from 'src/app/models/weather/weather-update';
import { WeatherService } from 'src/app/services/weather/weather.service';
import { first } from 'rxjs/operators';

import * as SunCalc from 'suncalc';
import * as moment from 'moment';
import 'moment-duration-format';

@Component({
    selector: 'app-almanac',
    templateUrl: './almanac.component.html',
    styleUrls: ['./almanac.component.scss']
})
export class AlmanacComponent implements OnInit {
    public loaded = false;
    public latestReading: WeatherUpdate;
    public sunTimes: SunCalc.GetTimesResult;
    public moonTimes: SunCalc.GetMoonTimes;
    public moon: SunCalc.GetMoonIlluminationResult;

    constructor(private weatherService: WeatherService) { }

    ngOnInit() {
        this.update();

        setInterval(() => this.update(), 60000);
    }

    async update() {
        this.weatherService.getLatestReading().pipe(first(r => r !== null)).subscribe(r => {
            this.latestReading = r;

            const date = new Date();

            this.sunTimes = SunCalc.getTimes(date, this.latestReading.Latitude, this.latestReading.Longitude);
            this.moonTimes = SunCalc.getMoonTimes(date, this.latestReading.Latitude, this.latestReading.Longitude);
            this.moon = SunCalc.getMoonIllumination(date);

            this.loaded = true;
        });
    }

    moonPhaseName(phase: number): string {
        if (phase === 0) {
            return 'New Moon';
        } else if (phase < 0.25) {
            return 'Waxing Crescent';
        } else if (phase === 0.25) {
            return 'First Quarter';
        } else if (phase < 0.5) {
            return 'Waxing Gibbous';
        } else if (phase === 0.5) {
            return 'Full Moon';
        } else if (phase < 0.75) {
            return 'Waning Gibbous';
        } else if (phase === 0.75) {
            return 'Last Quarter';
        } else if (phase < 1.0) {
            return 'Waning Crescent';
        }
    }

    moonPhaseLetter(phase: number): string {
        if (phase === 0) {
            return '0';
        } else if (phase < 0.25) {
            return 'D';
        } else if (phase === 0.25) {
            return 'G';
        } else if (phase < 0.5) {
            return 'I';
        } else if (phase === 0.5) {
            return '1';
        } else if (phase < 0.75) {
            return 'Q';
        } else if (phase === 0.75) {
            return 'T';
        } else if (phase < 1.0) {
            return 'W';
        }
    }

    dayLength(): string {
        const duration = moment.duration((this.sunTimes.sunset.valueOf() - this.sunTimes.sunrise.valueOf()));
        return duration.format('hh [hours] mm [minutes]');
    }
}

<div class="almanac-content">
    <div *ngIf="!loaded">
        Loading...
    </div>
    <div *ngIf="loaded">
        <table>
            <tr>
                <td class="almanac-table-header">
                    Sunrise
                </td>
                <td colspan="2">
                    {{ sunTimes!.sunrise | amLocal | amDateFormat: 'hh:mm:ss A' }}
                </td>
            </tr>
            <tr>
                <td class="almanac-table-header">
                    Sunset
                </td>
                <td colspan="2">
                    {{ sunTimes!.sunset | amLocal | amDateFormat: 'hh:mm:ss A' }}
                </td>
            </tr>
            <tr>
                <td class="almanac-table-header">
                    Day length
                </td>
                <td colspan="2">
                    {{ dayLength() }}
                </td>
            </tr>
            <tr>
                <td class="almanac-table-header">
                    Moonrise
                </td>
                <td colspan="2">
                    {{ moonTimes!.rise | amLocal | amDateFormat: 'hh:mm:ss A' }}
                </td>
            </tr>
            <tr>
                <td class="almanac-table-header">
                    Moonset
                </td>
                <td colspan="2">
                    {{ moonTimes!.set | amLocal | amDateFormat: 'hh:mm:ss A' }}
                </td>
            </tr>
            <tr>
                <td class="almanac-table-header">
                    Moon
                </td>
                <td>
                    {{ moonPhaseName(moon!.phase) }}
                    <br>
                    {{ (moon!.fraction * 100).toFixed(1) }}% illuminated
                </td>
                <td>
                    <div class="moon-phase">
                        {{ moonPhaseLetter(moon!.phase) }}
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>

// WebDisplay/src/components/almanac/main.tsx
import './main.scss';

import { useEffect, useState } from 'react';
import * as SunCalc from 'suncalc';
import DashboardItem from '../dashboard-item/main';
import WeatherService from '../../services/weather/main';
import WeatherRecent from '../../services/weather/weather-recent';
import { format, formatDuration, intervalToDuration } from 'date-fns';

function Almanac() {
    const [loaded, setLoaded] = useState<boolean>(false);
    const [sunTimes, setSunTimes] = useState<SunCalc.GetTimesResult | null>(null);
    const [moonTimes, setMoonTimes] = useState<SunCalc.GetMoonTimes | null>(null);
    const [moonIllumination, setMoonIllumination] = useState<SunCalc.GetMoonIlluminationResult | null>(null);

    const weatherService = new WeatherService();

    const dayLength = (): string => {
        const duration = intervalToDuration({
            start: sunTimes!.sunrise,
            end: sunTimes!.sunset,
        });

        return formatDuration(duration, { format: ['hours', 'minutes'] });
    };

    const moonPhaseName = (): string => {
        const phase = moonIllumination!.phase;

        if (phase === 0) {
            return 'New Moon';
        } else if (phase < 0.25) {
            return 'Waxing Crescent';
        } else if (phase === 0.25) {
            return 'First Quarter';
        } else if (phase < 0.5) {
            return 'Waxing Gibbous';
        } else if (phase === 0.5) {
            return 'Full Moon';
        } else if (phase < 0.75) {
            return 'Waning Gibbous';
        } else if (phase === 0.75) {
            return 'Last Quarter';
        } else if (phase < 1.0) {
            return 'Waning Crescent';
        }

        return '';
    };

    const moonPhaseLetter = (): string => {
        const phase = moonIllumination!.phase;

        if (phase === 0) {
            return '0';
        } else if (phase < 0.25) {
            return 'D';
        } else if (phase === 0.25) {
            return 'G';
        } else if (phase < 0.5) {
            return 'I';
        } else if (phase === 0.5) {
            return '1';
        } else if (phase < 0.75) {
            return 'Q';
        } else if (phase === 0.75) {
            return 'T';
        } else if (phase < 1.0) {
            return 'W';
        }

        return '';
    };

    useEffect(() => {
        weatherService.getLatest().then((weatherRecent: WeatherRecent) => {
            const date = new Date();

            setSunTimes(SunCalc.getTimes(date, weatherRecent?.latitude!, weatherRecent?.longitude!));
            setMoonTimes(SunCalc.getMoonTimes(date, weatherRecent?.latitude!, weatherRecent?.longitude!));
            setMoonIllumination(SunCalc.getMoonIllumination(date));

            setLoaded(true);
        });
    }, []);

    return (
        <DashboardItem title="Almanac">
            <div className="weather-current">
                {!loaded && <div>Loading...</div>}

                {loaded && (
                    <table>
                        <tbody>
                            <tr>
                                <td className="almanac-table-header">Sunrise</td>
                                <td colSpan={2}>{format(sunTimes!.sunrise, 'hh:mm:ss aa')}</td>
                            </tr>
                            <tr>
                                <td className="almanac-table-header">Sunset</td>
                                <td colSpan={2}>{format(sunTimes!.sunset, 'hh:mm:ss aa')}</td>
                            </tr>
                            <tr>
                                <td className="almanac-table-header">Day length</td>
                                <td colSpan={2}>{dayLength()}</td>
                            </tr>
                            <tr>
                                <td className="almanac-table-header">Moonrise</td>
                                <td colSpan={2}>{format(moonTimes!.rise, 'hh:mm:ss aa')}</td>
                            </tr>
                            <tr>
                                <td className="almanac-table-header">Moonset</td>
                                <td colSpan={2}>{format(moonTimes!.set, 'hh:mm:ss aa')}</td>
                            </tr>
                            <tr>
                                <td className="almanac-table-header">Moon</td>
                                <td>
                                    {moonPhaseName()}
                                    <br />
                                    {(moonIllumination!.fraction * 100).toFixed(1)}% illuminated
                                </td>
                                <td>
                                    <div className="moon-phase">{moonPhaseLetter()}</div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                )}
            </div>
        </DashboardItem>
    );
}

export default Almanac;
